# Generated by Django 6.0.1 on 2026-01-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name_plural': 'Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AddField(
            model_name='carrinho',
            name='session_key',
            field=models.CharField(default='sdasda'),
            preserve_default=False,
        ),
    ]
