# Generated by Django 6.0.1 on 2026-01-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_carrinho_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mercadoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipos'),
            preserve_default=False,
        ),
    ]
