# Generated by Django 6.0.1 on 2026-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_tipos_alter_item_preço_item_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipos',
            options={'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
