# Generated by Django 5.0.14 on 2026-02-15 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_tipos_options_alter_carrinho_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ItemImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='itens/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.item')),
            ],
        ),
    ]
